# Generated by Django 4.2 on 2024-06-09 13:19

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('category', models.CharField(choices=[('MED', 'Medieval Castle'), ('REN', 'Renaissance'), ('VIC', 'Victorian Mansion'), ('DRA', 'Dracula Castle'), ('FAF', 'Fairy Forest')], max_length=3)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('id', models.UUIDField(default=1, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
