# Generated by Django 4.2 on 2024-06-09 18:32

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(choices=[('Medieval Castle', 'Medieval Castle'), ('Renaissance Castle', 'Renaissance Castle'), ('Victorian Mansion', 'Victorian Mansion'), ('Dracula Castle', 'Dracula Castle'), ('Fairy Forest', 'Fairy Forest')], max_length=100)),
                ('category', models.CharField(choices=[('MED', 'Medieval'), ('REN', 'Renaissance'), ('VIC', 'Victorian'), ('DRA', 'Dracula'), ('FAF', 'Fairy Forest')], max_length=3)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
    ]
