# Generated by Django 4.2 on 2024-06-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0003_room_image_dinning_room_image_extra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='display_name',
            field=models.CharField(choices=[('medieval-castle', 'MEDIEVAL CASTLE'), ('renaissance-villa', 'RENAISSANCE VILLA'), ('victorian-mansion', 'VICTORIAN MANSION'), ('dracula-castle', 'DRACULA CASTLE'), ('fairy-forest', 'FAIRY FOREST')], max_length=100),
        ),
    ]
