# Generated by Django 4.2 on 2024-06-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worlds', '0005_alter_room_display_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='display_name',
            field=models.CharField(choices=[('MEDIEVAL CASTLE', 'MEDIEVAL CASTLE'), ('RENAISSANCE VILLA', 'RENAISSANCE VILLA'), ('VICTORIAN MANSION', 'VICTORIAN MANSION'), ('DRACULA CASTLE', 'DRACULA CASTLE'), ('FAIRY FOREST', 'FAIRY FOREST')], max_length=100),
        ),
    ]
